name: Deploy Main Branch

on:
  push:
    branches:
      - main
      - deploy-action

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site
      run: |
        npm i
        npm run build
        mv dist webxdc
    - name: Upload
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        host: "delta.chat"
        port: 22
        local: "webxdc"
        remote: "/var/www/html/"
